# Linkedin authentication key

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = '77pcykjfo9eng7'
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = 'KURzCzu1T4TqiRBT'

# Redirect urls

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'